name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCE_HOST }}
        username: troorl
        key: ${{ secrets.GCE_KEY }}
        script: |
          rm -rf ${{ PROJ_NAME }}
          git clone https://github.com/sunabozu/${{ PROJ_NAME }}.git
          git status
          cd ${{ PROJ_NAME }}
          npm i
          pm2 restart ${{ PROJ_NAME }}