name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 35.238.217.64
        username: troorl
        key: ${{ secrets.GCE_KEY }}
        script: |
          rm -rf binance-price-change
          git clone https://github.com/sunabozu/binance-price-change.git
          git status
          cd binance-price-change
          npm i